---

- name: To-display-the-outpu-of-encrypted-file
  hosts: build_servers
  vars:
    mydata: "{{lookup('file', 'file1.') }}"
  tasks:
    - include_vars: file1.
    - name: printing the output
      debug:
        var: db_password

    

